### ISSUE TITLE
阿里云资源站，网速杠杠的

### ISSUE THREAD

**Issue by 15531700396** [Hunlongyu/ZY-Player#595]
可以添加一下播放mp4的功能吗
http://www.cqzyw.net:88/
蓝光$https://mp4.cqzyw.net:300/bffc0bd7-c24f-4641-9f8e-11f06c3c6a87.mp4

![捕获10](https://user-images.githubusercontent.com/65349532/102689915-d2f9f680-423c-11eb-99ff-784bf53f8724.PNG)
就是使这个网站可以访问和正常播放

**Comment by cuiocean** [comment]
请设置有意义的标题

**Comment by cuiocean** [comment]
我试了一下 它提供的api返回的不是mp4链接

**Comment by buvta** [comment]
api返回的是mp4、m3u8、纯链接混杂

**Comment by buvta** [comment]
已支持mp4格式源，请等待新版本发布

**Comment by i-loli** [comment]
还有他的地址么？没保存。

**Comment by buvta** [comment]
网站没了

**Comment by i-loli** [comment]
好的，谢谢回复！只是看见许多影视站依旧在用这家的资源。
---原始邮件---
发件人:&quot;buvta&quot;<notifications@github.com&gt;
发送时间:2021年1月23日 星期六 下午9:31
收件人:&quot;Hunlongyu/ZY-Player&quot;<ZY-Player@noreply.github.com&gt;
抄送:&quot;龙柳夜童欣&quot;<2209901700@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [Hunlongyu/ZY-Player] 阿里云资源站，网速杠杠的 (#595)



网站没了

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
