### ISSUE TITLE
This dependency was not found:  * regenerator-runtime/runtime

### ISSUE THREAD

**Issue by idootop** [Hunlongyu/ZY-Player#98]
clone下来项目之后，npm install安装好依赖，然后run dev,提示
This dependency was not found:  * regenerator-runtime/runtime
看了下报错的文件，都是有async异步函数，请问这个问题应该咋解决？
![Snipaste_2020-06-11_15-11-22](https://user-images.githubusercontent.com/35302658/84356076-3fdd6580-abf6-11ea-9b7d-b0ddc854cae6.png)

**Comment by Hunlongyu** [comment]
建议尝试使用 yarn 安装依赖.
我这边使用 npm 会经常出错, 即使电脑 fq 了,也会安装依赖失败.

**Comment by idootop** [comment]
> 
> 
> 建议尝试使用 yarn 安装依赖.
> 我这边使用 npm 会经常出错, 即使电脑 fq 了,也会安装依赖失败.

我之前用的是pnpm，我再去试下

**Comment by idootop** [comment]
> 
> 
> 建议尝试使用 yarn 安装依赖.
> 
> ```shell
> git clone h...
> cd ZY-Player
> yarn
> yarn dev
> ```
> 
> 我这边使用 npm 会经常出错, 即使电脑 fq 了,也会安装依赖失败.

可以了，谢谢

**Comment by Angle-bo** [comment]
yarn dev 允许，警告，这个有遇到吗。 

warning  in ./src/components/Star.vue?vue&type=template&id=24853982&scoped=true
&

Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) Do not use v-for index as key on
 <transition-group> children, this is the same as not using keys.

 @ ./src/components/Star.vue?vue&type=template&id=24853982&scoped=true& 1:0-421
1:0-421
 @ ./src/components/Star.vue
 @ ./src/components/register.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.33.107:8081&sockPath=/sockjs
-node (webpack)/hot/dev-server.js ./src/main.js
